# GitHub Actions for PostGIS
#
# Paul Ramsey <pramsey at cleverelephant dot ca>

name: "CI"
on: [push, pull_request]

jobs:
  linux:

    runs-on: ubuntu-20.04

    env:
      PGVER: 10
      OS_NAME: focal-pgdg
      OS_PGVER: 14


    name: "CI"
    strategy:
      matrix:
        ci:
        - { PGVER: 10 }
        # - { PGVER: 11 }
        # - { PGVER: 12 }
        # - { PGVER: 13 }
        # - { PGVER: 14 }

    steps:

    - name: 'Check Out'
      uses: actions/checkout@v2

    - name: 'Uninstall PostgreSQL'
      run: |
        sudo apt-get -y -f --ignore-missing --purge remove postgresql postgresql-common postgresql-$OS_PGVER postgresql-server-dev-$OSPGVER postgresql-client-common postgresql-client-$OSPGVER libpq-dev
        sudo apt-get -y autoremove
        sudo rm -rf /var/lib/postgresql

    - name: 'Install PostgreSQL'
      run: |
        export PGVER=${{ matrix.ci.PGVER }}
        export PGDATA=/var/lib/postgresql/$PGVER/main
        export PGETC=/etc/postgresql/$PGVER/main
        export PGBIN=/usr/lib/postgresql/$PGVER/bin
        curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        sudo add-apt-repository "deb http://apt.postgresql.org/pub/repos/apt/ $OS_NAME main $PGVER"
        sudo apt-get -y install libcurl4-gnutls-dev postgresql-server-dev-$PGVER postgresql-client-$PGVER postgresql-$PG_VERSION
        sudo $PGBIN/pg_ctlcluster $PGVER main stop
        sudo cp ./ci/pg_hba.conf $PGETC/pg_hba.conf
        sudo $PGBIN/pg_ctlcluster $PGVER main start

    - name: 'Build & Test'
      run: |
        export PATH=/usr/lib/postgresql/$PGVER/bin/:$PATH
        make
        sudo make install
        PGUSER=postgres make installcheck || (cat regression.diffs && /bin/false)
